




@host=http://localhost:5068

GET {{host}}/port/getallportsasync
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiU2ViYXN0aWFuIEJyZW1lciIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InNlYkBnLmRlIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiTm9ybWFsVXNlciIsImV4cCI6MTY5NzU2MDc1MywiaXNzIjoiU2VjdGlvbk1hbmFnZW1lbnQiLCJhdWQiOiJTZWN0aW9uTWFuYWdlbWVudCJ9.my4mnhj72WWHcsnppi0D9TSDtdMb0m2hnO4OIB7ETpQ

